directories:
  output: release-test2
  buildResources: build
appId: com.switchfast.app
productName: switchfast
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
icon: src/assets/logo 256.png
win:
  icon: src/assets/logo 256.png
  target:
    - nsis
publish:
  - provider: github
    owner: SebSte85
    repo: switchfast
extraMetadata:
  environment: test
  testStripeSecretKey: ''
  testStripePriceId: ''
electronVersion: 27.3.11
